### ISSUE TITLE
run demo 

### ISSUE THREAD

**Issue by betterhalfwzm** [open-mmlab/mmflow#132]
parser.add_argument('--config',default='configs/liteflownet2/liteflownet2_ft_4x1_500k_kitti_320x896.py',  help='Config file')
    parser.add_argument('--checkpoint', default='models/liteflownet2/liteflownet2_ft_4x1_500k_kitti_320x896.pth', help='Checkpoint file')

Traceback (most recent call last):
  File "/home/wangzhaoming/workspace/code/mmflow/demo/image_demo.py", line 44, in <module>
    main(args)
  File "/home/wangzhaoming/workspace/code/mmflow/demo/image_demo.py", line 35, in main
    result = inference_model(model, 'demo/frame_0001.png', 'demo/frame_0002.png')
  File "/disk/workspace/wangzhaoming/code/mmflow/mmflow/apis/inference.py", line 115, in inference_model
    data = test_pipeline(data)
  File "/disk/workspace/wangzhaoming/code/mmflow/mmflow/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/disk/workspace/wangzhaoming/code/mmflow/mmflow/datasets/pipelines/loading.py", line 146, in __call__
    results = self._load_sparse_flow(results)
  File "/disk/workspace/wangzhaoming/code/mmflow/mmflow/datasets/pipelines/loading.py", line 190, in _load_sparse_flow
    filenames = list(results['ann_info'].keys())
KeyError: 'ann_info'

**Comment by MeowZheng** [comment]
Thanks for your bug report, I'll fix it asap.
