### ISSUE TITLE
Input resolution error

### ISSUE THREAD

**Issue by makecent** [open-mmlab/mmflow#178]
I found some model cannot handle input resolution even divided by 16, e.g. 224 or 240.

An example:
```python
import torch
from mmflow.apis import init_model

# Specify the path to model config and checkpoint file
config_file = 'configs/pwcnet_plus_8x1_750k_sintel_kitti2015_hd1k_320x768.py'
checkpoint_file = 'checkpoints/pwcnet_plus_8x1_750k_sintel_kitti2015_hd1k_320x768.pth'

# build the model from a config file and a checkpoint file
model = init_model(config_file, checkpoint_file, device='cuda:0')
with torch.no_grad():
    out = model(imgs=torch.rand(1, 6, 224, 224).cuda()) 
```
Error:
```shell
Traceback (most recent call last):
  File "/home/louis/PycharmProjects/mmflow/memory_and_speed.py", line 21, in <module>
    out = model(imgs=torch.rand(1, 6, 224, 224).cuda())
  File "/home/louis/miniconda3/envs/mmflow/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/louis/miniconda3/envs/mmflow/lib/python3.10/site-packages/mmflow/models/flow_estimators/base.py", line 61, in forward
    return self.forward_test(*args, **kwargs)
  File "/home/louis/miniconda3/envs/mmflow/lib/python3.10/site-packages/mmflow/models/flow_estimators/pwcnet.py", line 90, in forward_test
    return self.decoder.forward_test(feat1, feat2, H, W, img_metas)
  File "/home/louis/miniconda3/envs/mmflow/lib/python3.10/site-packages/mmflow/models/decoders/pwcnet_decoder.py", line 320, in forward_test
    flow_pred = self.forward(feat1, feat2)
  File "/home/louis/miniconda3/envs/mmflow/lib/python3.10/site-packages/mmflow/models/decoders/pwcnet_decoder.py", line 258, in forward
    corr_feat = torch.cat((corr_feat_, _feat1, upflow, upfeat),
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 7 but got size 8 for tensor number 2 in the list.
```

Images with side of 240 and 224 result in error while 256 does not.

**Comment by makecent** [comment]
Seems like we could use `InputPad ` to avoid this error. It's just only few methods, e.g., gma, are using `InputPad`, the others using `InputResize` instead and are very likely to got error. 

https://github.com/open-mmlab/mmflow/blob/99154a1769ab3a65900f24baf82086580e199f70/configs/_base_/datasets/sintel_cleanx100_sintel_fianlx100_kitti2015x200_hd1kx5_flyingthings3d_raft_384x768.py#L43
