### ISSUE TITLE
Operation Error [Assertion failed) !dsize.empty() in function 'resize']

### ISSUE THREAD

**Issue by fusang1337** [open-mmlab/mmflow#57]
### Demo running as follows is not an error, prove is not an environmental problem
`
from mmflow.apis import inference_model, init_model
config_file = 'configs/pwcnet/pwcnet_ft_4x1_300k_sintel_final_384x768.py'
checkpoint_file = 'checkpoints/pwcnet_ft_4x1_300k_sintel_final_384x768.pth'
device = 'cuda:0'
model = init_model(config_file, checkpoint_file, device=device)
inference_model(model, 'demo/frame_0001.png', 'demo/frame_0002.png')
`
### It’s OK to call the video demo with the following command
`
python demo/video_demo.py "/home/thhicv/program/mmflow/demo/demo.mp4" 'configs/pwcnet/pwcnet_ft_4x1_300k_sintel_final_384x768.py' 'checkpoints/pwcnet_ft_4x1_300k_sintel_final_384x768.pth' /home/thhicv/program/mmflow/demo/xx1x.mp4
`
### When I change the video file, it’s an error
`/home/thhicv/anaconda3/envs/mmflow/bin/python /home/thhicv/program/mmflow/demo/video_demo.py /home/thhicv/视频/flow/溪丁灯.mp4 configs/pwcnet/pwcnet_ft_4x1_300k_sintel_final_384x768.py checkpoints/pwcnet_ft_4x1_300k_sintel_final_384x768.pth /home/thhicv/视频/flow/溪丁灯.mp4_flow.mp4`
### LOG：
`Traceback (most recent call last):
  File "/home/thhicv/program/mmflow/demo/video_demo.py", line 143, in <module>
    main(args)
  File "/home/thhicv/program/mmflow/demo/video_demo.py", line 83, in main
    result = inference_model(model, img1, img2)
  File "/home/thhicv/program/mmflow/mmflow/apis/inference.py", line 115, in inference_model
    data = test_pipeline(data)
  File "/home/thhicv/program/mmflow/mmflow/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home/thhicv/program/mmflow/mmflow/datasets/pipelines/transforms.py", line 428, in __call__
    imgs, scale_factor = self._resize_img(imgs)
  File "/home/thhicv/program/mmflow/mmflow/datasets/pipelines/transforms.py", line 451, in _resize_img
    img_ = mmcv.imresize(img, (newW, newH), return_scale=False)
  File "/home/thhicv/anaconda3/envs/mmflow/lib/python3.7/site-packages/mmcv/image/geometric.py", line 89, in imresize
    img, size, dst=out, interpolation=cv2_interp_codes[interpolation])
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-l1r0y34w/opencv/modules/imgproc/src/resize.cpp:3688: error: (-215:Assertion failed) !dsize.empty() in function 'resize'
`

**Comment by MeowZheng** [comment]
What is the frame shape in '/home/thhicv/视频/flow/溪丁灯.mp4'? From the log you provided, the shape of frame might be not (H, W, C).

**Comment by fusang1337** [comment]
1、[[文件在这里](https://wss1.cn/f/74zb36gzeu8)]的尺寸为 1280 × 720
2、在video_demo内45行size为(720, 1280)
3、在video_demo内54行while循环内的[flag, img = cap.read()]的img的shape是(1280, 720, 3)
4、在mmflow/datasets/pipelines/transforms.py内的445行 H=1280 W=720

**Comment by fusang1337** [comment]
1、[文件在下面]的尺寸为 1280 × 720
2、在video_demo内45行size为(720, 1280)
3、在video_demo内54行while循环内的[flag, img = cap.read()]的img的shape是(1280, 720, 3)
4、在mmflow/datasets/pipelines/transforms.py内的445行 H=1280 W=720

**Comment by fusang1337** [comment]
`Traceback (most recent call last):
  File "demo/video_demo.py", line 148, in <module>
    main(args)
  File "demo/video_demo.py", line 88, in main
    result = inference_model(model, img1, img2)
  File "/home/thhicv/program/mmflow/mmflow/apis/inference.py", line 134, in inference_model
    results = model(test_mode=True, **data)
  File "/home/thhicv/anaconda3/envs/mmflow/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/thhicv/program/mmflow/mmflow/models/flow_estimators/base.py", line 61, in forward
    return self.forward_test(*args, **kwargs)
  File "/home/thhicv/program/mmflow/mmflow/models/flow_estimators/pwcnet.py", line 92, in forward_test
    return self.decoder.forward_test(feat1, feat2, H, W, img_metas)
  File "/home/thhicv/program/mmflow/mmflow/models/decoders/pwcnet_decoder.py", line 321, in forward_test
    flow_pred = self.forward(feat1, feat2)
  File "/home/thhicv/program/mmflow/mmflow/models/decoders/pwcnet_decoder.py", line 259, in forward
    dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 46 and 45 (The offending index is 0)
`

**Comment by MeowZheng** [comment]
I just tried 
```
/home/thhicv/anaconda3/envs/mmflow/bin/python /home/thhicv/program/mmflow/demo/video_demo.py /home/thhicv/视频/flow/溪丁灯.mp4 configs/pwcnet/pwcnet_ft_4x1_300k_sintel_final_384x768.py checkpoints/pwcnet_ft_4x1_300k_sintel_final_384x768.pth /home/thhicv/视频/flow/溪丁灯.mp4_flow.mp4
```
but I didn't reproduce the bug

**Comment by MeowZheng** [comment]
new discussion in #64
