### ISSUE TITLE
Some new issues for single GPU training

### ISSUE THREAD

**Issue by ckcraig01** [open-mmlab/mmflow#77]
1. with this command
``` shell  
python tools/train.py configs/raft/raft_8x2_100k_flyingchairs_368x496.py --gpu-ids 0
```
The error is **RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.**

2. Then I try this command
``` shell  
 python tools/train.py configs/raft/raft_8x2_100k_flyingchairs_368x496.py --gpu-ids 0 --launcher pytorch
```

The error becomes:
``` console
rank = int(os.environ['RANK'])
  File "/home/miniconda3/envs/mmflow/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```

3. Then I add following code to train.py:
``` shell  
if 'RANK' not in os.environ:
        os.environ['RANK'] = str(args.local_rank)
```
The error is:
**ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable WORLD_SIZE expected, but not set**

4. Then I add  following code to train.py:
``` shell  
if 'WORLD_SIZE' not in os.environ:
        os.environ['WORLD_SIZE'] = str(1)
```
The error is:
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable MASTER_ADDR expected, but not set

5. Then I have setup the MASTER_ADDR and MASTER PORT in similar way,

I got this error:
```
Traceback (most recent call last):
  File "tools/train.py", line 199, in <module>
    main()
  File "tools/train.py", line 188, in main
    train_model(
  File "/home/framework/optical_flow/mmflow/mmflow/apis/train.py", line 212, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/miniconda3/envs/mmflow/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/miniconda3/envs/mmflow/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/home/miniconda3/envs/mmflow/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/miniconda3/envs/mmflow/lib/python3.8/site-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/miniconda3/envs/mmflow/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/miniconda3/envs/mmflow/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 128, 46, 62]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

Hope I have addressed the issue clear enough. Thank for your help

**Comment by MeowZheng** [comment]
I think if you only use one GPU to train, just run following command
```
python tools/train.py configs/raft/raft_8x2_100k_flyingchairs_368x496.py
```

**Comment by ckcraig01** [comment]
Solved, it is environmental issue with pytorch 1.10 and cudatoolkit 11.3,

It work with following flow:
```shell
conda create -n mmflow python=3.8 conda -y
conda activate mmflow
conda install pytorch==1.9.0 torchvision==0.10.0 cudatoolkit=11.1 -c pytorch -c conda-forge
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
pip install -r requirements/build.txt
pip install -v -e . 
pip install tensorboard
```
